import path from "node:path";
import { chromium } from "playwright";
import { marked } from "marked";
import sanitizeHtml from "sanitize-html";

type Preset = "report" | "notes" | "resume";

function presetTitle(preset: Preset) {
  if (preset === "resume") return "Resume";
  if (preset === "notes") return "Notes";
  return "Report";
}

export async function renderPdf(opts: {
  id: string;
  rawText: string;
  preset: Preset;
  outDir: string;
}): Promise<{ filePath: string; fileName: string }> {
  const { id, rawText, preset, outDir } = opts;

  const fileName = `${preset}-${id}.pdf`;
  const filePath = path.join(outDir, fileName);

  const rawHtml = marked.parse(rawText) as string;
  const safeHtml = sanitizeHtml(rawHtml, {
    allowedTags: sanitizeHtml.defaults.allowedTags.concat([
      "img",
      "h1",
      "h2",
      "pre",
      "code",
    ]),
    allowedAttributes: { a: ["href", "name", "target", "rel"] },
  });
  const title = presetTitle(preset);

  const html = `<!doctype html>
<html>
<head>
  <meta charset="utf-8" />
  <title>${title}</title>
  <style>
    @page { margin: 28mm 18mm; }
    body {
      font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;
      color: #111;
      line-height: 1.5;
      font-size: 12.5pt;
    }
    h1 {
      font-size: 22pt;
      margin: 0 0 12mm 0;
      letter-spacing: -0.02em;
    }
    .meta {
      font-size: 10pt;
      color: #666;
      margin-bottom: 8mm;
    }
    .content {
      white-space: normal;
      word-wrap: break-word;
    }
    .rule {
      height: 1px;
      background: #eee;
      margin: 8mm 0;
    }
    .content h1, .content h2, .content h3 { margin: 10mm 0 4mm; }
    .content p { margin: 0 0 4mm; }
    .content ul, .content ol { margin: 0 0 4mm 6mm; }
    .content pre {
    background: #f6f8fa;
    padding: 10px 12px;
    border-radius: 6px;
    overflow: hidden;
    font-size: 10.5pt;
    }
    .content code { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; }
  </style>
</head>
<body>
  <h1>${title}</h1>
  <div class="meta">Generated by PDF Exporter</div>
  <div class="rule"></div>
  <div class="content">${safeHtml}</div>
</body>
</html>`;

  const browser = await chromium.launch();
  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: "load" });

    await page.pdf({
      path: filePath,
      format: "A4",
      printBackground: true,
    });

    return { filePath, fileName };
  } finally {
    await browser.close();
  }
}
